# Site settings
email: bikeswap@brazendropouts.org
baseurl: ""
url: "http://www.bdbikeswap.com"
analyticsId: "UA-10557556-2"
starts_at: 2015-01-10T09:00:00
stops_at: 2015-01-10T15:00:00
venue: Alliant Energy Center

# Build settings
markdown: kramdown
